version: '3.8'

services:
#  cards:
#    container_name : card
#    image: vineet1288/card:latest
#    ports:
#      - "8081:8081"
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.0
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kakfa:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT : zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.1.3:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    depends_on:
      - zookeeper

