DROP TABLE IF EXISTS CARDDETAILS;

CREATE TABLE CARDDETAILS (
  id BIGINT auto_increment PRIMARY KEY,
  card_number VARCHAR(20) NOT NULL,
  name VARCHAR(250) NOT NULL,
  balance VARCHAR(25) NOT NULL,
  card_limit VARCHAR(25) NOT NULL
);